# Generated by Django 5.0.2 on 2024-04-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_autordb_fecha_fallecimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75, verbose_name='nombre')),
            ],
        ),
        migrations.AlterModelOptions(
            name='frasedb',
            options={'verbose_name': 'Frase', 'verbose_name_plural': 'Frases'},
        ),
        migrations.AddField(
            model_name='autordb',
            name='profesion',
            field=models.ManyToManyField(to='app1.profesiondb', verbose_name='Profesion'),
        ),
    ]
